dist: jammy

language: go

services:
  - docker

env:
  global:
    - FORCE_COLOR=1

install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - sudo docker run --privileged --rm tonistiigi/binfmt --install all
  - sudo wget https://github.com/earthly/earthly/releases/latest/download/earthly-linux-amd64 -O /usr/local/bin/earthly
  - sudo chmod +x /usr/local/bin/earthly
  - sudo earthly bootstrap --with-autocomplete

_earthly: &earthly
  script:
    - cd $TRAVIS_JOB_NAME
    - sudo earthly --ci --allow-privileged --push +all

jobs:
  include:
    - name: alpine
      <<: *earthly

    - name: ssh
      depends_on: alpine
      <<: *earthly
    - name: s2h
      depends_on: alpine
      <<: *earthly
    - name: makeself
      depends_on: alpine
      <<: *earthly
    - name: derper
      depends_on: alpine
      <<: *earthly
    - name: container-cli
      depends_on: alpine
      <<: *earthly
    - name: aria2
      depends_on: alpine
      <<: *earthly
    - name: bandwagonmon
      depends_on: alpine
      <<: *earthly
    - name: ddns
      depends_on: alpine
      <<: *earthly
    - name: dnsacme
      depends_on: alpine
      <<: *earthly
    - name: idgen
      depends_on: alpine
      <<: *earthly
    - name: notibot
      depends_on: alpine
      <<: *earthly
    - name: clash-meta
      depends_on: alpine
      <<: *earthly
