dist: jammy

language: go

services:
  - docker

env:
  global:
    - FORCE_COLOR=1

install:
  - echo "$DOCKER_PASSWORD" | docker login ghcr.io -u "$DOCKER_USERNAME" --password-stdin
  - sudo docker run --privileged --rm tonistiigi/binfmt --install all
  - sudo wget https://github.com/earthly/earthly/releases/latest/download/earthly-linux-amd64 -O /usr/local/bin/earthly
  - sudo chmod +x /usr/local/bin/earthly
  - sudo earthly bootstrap --with-autocomplete

_earthly: &earthly
  script:
    - cd $TRAVIS_JOB_NAME
    - sudo earthly --ci --allow-privileged --push +all

jobs:
  include:
    - name: dockerhub
      stage: sync-base-image
      <<: *earthly

    - name: alpine
      stage: alpine
      <<: *earthly

    - name: caddy
      stage: standalone
      <<: *earthly
    - name: nodebuild
      stage: standalone
      <<: *earthly
    - name: openjdk
      stage: standalone
      <<: *earthly
    - name: open-vm-tools
      stage: standalone
      <<: *earthly
    - name: nginx-singlepage
      stage: standalone
      <<: *earthly
    - name: demo
      stage: standalone
      <<: *earthly
    - name: poetbot
      stage: standalone
      <<: *earthly
    - name: jira
      stage: standalone
      <<: *earthly
    - name: confluence
      stage: standalone
      <<: *earthly

    - name: ssh
      stage: alpine-base
      <<: *earthly
    - name: s2h
      stage: alpine-base
      <<: *earthly
    - name: makeself
      stage: alpine-base
      <<: *earthly
    - name: derper
      stage: alpine-base
      <<: *earthly
    - name: container-cli
      stage: alpine-base
      <<: *earthly
    - name: aria2
      stage: alpine-base
      <<: *earthly
    - name: bandwagonmon
      stage: alpine-base
      <<: *earthly
    - name: ddns
      stage: alpine-base
      <<: *earthly
    - name: dnsacme
      stage: alpine-base
      <<: *earthly
    - name: idgen
      stage: alpine-base
      <<: *earthly
    - name: notibot
      stage: alpine-base
      <<: *earthly
    - name: clash-meta
      stage: alpine-base
      <<: *earthly
