version: '3'

tasks:
  install-pkgs:
    cmds:
      - sudo apt update -y
      - sudo apt install curl jq qemu binfmt-support qemu-user-static -y
  install-earthly:
    deps: [install-pkgs]
    vars:
      EARTHLY_DOWNLOAD_URL:
        sh: curl -fsSL https://api.github.com/repos/earthly/earthly/releases/latest | jq -r '.assets[].browser_download_url' | grep earthly-linux-amd64
    cmds:
      - sudo curl -fsSL {{.EARTHLY_DOWNLOAD_URL}} > /usr/local/bin/earthly
      - sudo chmod +x /usr/local/bin/earthly
  earthly-build:
    deps: [install-earthly]
    cmds:
      - earthly --allow-privileged --push +all
  alpine:
    dir: {{.TASK}}
    cmds:
      - task: earthly-build
