name: All In One

on:
  schedule:
    - cron: 0 16 * * 1
  workflow_dispatch:
    inputs:
      trigger:
        description: Manually trigger
        required: true
        type: choice
        options:
          - alpine
          - alpine-base
          - standalone


env:
  FORCE_COLOR: 1
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}

jobs:
  alpine:
    runs-on: ubuntu-latest
    concurrency: alpine
    if: contains(github.event.inputs.trigger, ${{ github.job }}, alpine-base, all) || github.event_name == schedule
    steps:
    - name: Init Earthly
      uses: mritd/init-earthly-action@main
    - name: Earthly Build
      working-directory: ${{ github.job }}
      run: earthly --allow-privileged --push +all

  alpine-base:
    needs: alpine
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      max-parallel: 3
      matrix:
        directory:
          - ssh
          - s2h
          - makeself
          - derper
          - container-cli
          - aria2
          - bandwagonmon
          - ddns
          - dnsacme
          - idgen
          - notibot
          - clash-meta
    steps:
    - name: Init Earthly
      uses: mritd/init-earthly-action@main
    - name: Earthly Build
      working-directory: ${{ matrix.directory }}
      run: earthly --allow-privileged --push +all


  standalone:
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      max-parallel: 3
      matrix:
        directory:
          - caddy
          - nodebuild
          - openjdk
          - open-vm-tools
          - nginx-singlepage
    steps:
    - name: Init Earthly
      uses: mritd/init-earthly-action@main
    - name: Earthly Build
      working-directory: ${{ matrix.directory }}
      run: earthly --allow-privileged --push +all
