name: All In One

on:
  schedule:
    - cron: 0 16 * * 1
  workflow_dispatch:
    inputs:
      trigger:
        description: Manually trigger
        required: true
        type: choice
        options:
          - build

jobs:
  alpine:
    uses: ./.github/workflows/.earthly.yaml
    secrets: inherit
    with:
      build-dir: alpine
  aria2:
    uses: ./.github/workflows/.earthly.yaml
    secrets: inherit
    with:
      build-dir: aria2
  asuswrt-merlin-build:
    uses: ./.github/workflows/.earthly.yaml
    secrets: inherit
    with:
      build-dir: asuswrt-merlin-build
  bandwagonmon:
    uses: ./.github/workflows/.earthly.yaml
    secrets: inherit
    with:
      build-dir: bandwagonmon
  caddy:
    uses: ./.github/workflows/.earthly.yaml
    secrets: inherit
    with:
      build-dir: caddy
  clash-meta:
    uses: ./.github/workflows/.earthly.yaml
    secrets: inherit
    with:
      build-dir: clash-meta
  confluence:
    uses: ./.github/workflows/.earthly.yaml
    secrets: inherit
    with:
      build-dir: confluence
  container-cli:
    uses: ./.github/workflows/.earthly.yaml
    secrets: inherit
    with:
      build-dir: container-cli
  ddns:
    uses: ./.github/workflows/.earthly.yaml
    secrets: inherit
    with:
      build-dir: ddns
  demo:
    uses: ./.github/workflows/.earthly.yaml
    secrets: inherit
    with:
      build-dir: demo
  derper:
    uses: ./.github/workflows/.earthly.yaml
    secrets: inherit
    with:
      build-dir: derper
  dnsacme:
    uses: ./.github/workflows/.earthly.yaml
    secrets: inherit
    with:
      build-dir: dnsacme
  dockerhub:
    uses: ./.github/workflows/.earthly.yaml
    secrets: inherit
    with:
      build-dir: dockerhub
  idgen:
    uses: ./.github/workflows/.earthly.yaml
    secrets: inherit
    with:
      build-dir: idgen
  jira:
    uses: ./.github/workflows/.earthly.yaml
    secrets: inherit
    with:
      build-dir: jira
  makeself:
    uses: ./.github/workflows/.earthly.yaml
    secrets: inherit
    with:
      build-dir: makeself
  nginx-singlepage:
    uses: ./.github/workflows/.earthly.yaml
    secrets: inherit
    with:
      build-dir: nginx-singlepage
  nodebuild:
    uses: ./.github/workflows/.earthly.yaml
    secrets: inherit
    with:
      build-dir: nodebuild
  notibot:
    uses: ./.github/workflows/.earthly.yaml
    secrets: inherit
    with:
      build-dir: notibot
  open-vm-tools:
    uses: ./.github/workflows/.earthly.yaml
    secrets: inherit
    with:
      build-dir: open-vm-tools
  openjdk:
    uses: ./.github/workflows/.earthly.yaml
    secrets: inherit
    with:
      build-dir: openjdk
  osarch:
    uses: ./.github/workflows/.earthly.yaml
    secrets: inherit
    with:
      build-dir: osarch
  poetbot:
    uses: ./.github/workflows/.earthly.yaml
    secrets: inherit
    with:
      build-dir: poetbot
  s2h:
    uses: ./.github/workflows/.earthly.yaml
    secrets: inherit
    with:
      build-dir: s2h
  ssh:
    uses: ./.github/workflows/.earthly.yaml
    secrets: inherit
    with:
      build-dir: ssh
