name: All In One

on:
  schedule:
    - cron: 0 16 * * 1
  workflow_dispatch:
    inputs:
      trigger:
        description: Manually trigger
        required: true
        type: choice
        options:
          - build

jobs:
  alpine:
    uses: ./.github/workflows/.earthly.yaml
    secrets: inherit
    with:
      build-dir: alpine

  aria2:
    needs:
      - alpine
    uses: ./.github/workflows/.earthly.yaml
    with:
      build-dir: aria2
  asuswrt-merlin-build:
    needs:
      - aria2
    uses: ./.github/workflows/.earthly.yaml
    with:
      build-dir: asuswrt-merlin-build
  bandwagonmon:
    needs:
      - asuswrt-merlin-build
    uses: ./.github/workflows/.earthly.yaml
    with:
      build-dir: bandwagonmon
  caddy:
    needs:
      - bandwagonmon
    uses: ./.github/workflows/.earthly.yaml
    with:
      build-dir: caddy
  clash-meta:
    needs:
      - caddy
    uses: ./.github/workflows/.earthly.yaml
    with:
      build-dir: clash-meta
  confluence:
    needs:
      - clash-meta
    uses: ./.github/workflows/.earthly.yaml
    with:
      build-dir: confluence
  container-cli:
    needs:
      - confluence
    uses: ./.github/workflows/.earthly.yaml
    with:
      build-dir: container-cli
  ddns:
    needs:
      - container-cli
    uses: ./.github/workflows/.earthly.yaml
    with:
      build-dir: ddns
  demo:
    needs:
      - ddns
    uses: ./.github/workflows/.earthly.yaml
    with:
      build-dir: demo
  derper:
    needs:
      - demo
    uses: ./.github/workflows/.earthly.yaml
    with:
      build-dir: derper
  dnsacme:
    needs:
      - derper
    uses: ./.github/workflows/.earthly.yaml
    with:
      build-dir: dnsacme
  dockerhub:
    needs:
      - dnsacme
    uses: ./.github/workflows/.earthly.yaml
    with:
      build-dir: dockerhub
  idgen:
    needs:
      - dockerhub
    uses: ./.github/workflows/.earthly.yaml
    with:
      build-dir: idgen
  jira:
    needs:
      - idgen
    uses: ./.github/workflows/.earthly.yaml
    with:
      build-dir: jira
  makeself:
    needs:
      - jira
    uses: ./.github/workflows/.earthly.yaml
    with:
      build-dir: makeself
  nginx-singlepage:
    needs:
      - makeself
    uses: ./.github/workflows/.earthly.yaml
    with:
      build-dir: nginx-singlepage
  nodebuild:
    needs:
      - nginx-singlepage
    uses: ./.github/workflows/.earthly.yaml
    with:
      build-dir: nodebuild
  notibot:
    needs:
      - nodebuild
    uses: ./.github/workflows/.earthly.yaml
    with:
      build-dir: notibot
  open-vm-tools:
    needs:
      - notibot
    uses: ./.github/workflows/.earthly.yaml
    with:
      build-dir: open-vm-tools
  openjdk:
    needs:
      - open-vm-tools
    uses: ./.github/workflows/.earthly.yaml
    with:
      build-dir: openjdk
  osarch:
    needs:
      - openjdk
    uses: ./.github/workflows/.earthly.yaml
    with:
      build-dir: osarch
  poetbot:
    needs:
      - osarch
    uses: ./.github/workflows/.earthly.yaml
    with:
      build-dir: poetbot
  s2h:
    needs:
      - poetbot
    uses: ./.github/workflows/.earthly.yaml
    with:
      build-dir: s2h
  ssh:
    needs:
      - s2h
    uses: ./.github/workflows/.earthly.yaml
    with:
      build-dir: ssh

