name: All In One

on:
  schedule:
    - cron: 0 16 * * 1
  workflow_dispatch:
    inputs:
      trigger:
        description: Manually trigger
        required: true
        type: choice
        options:
          - build

jobs:
  alpine:
    runs-on: ubuntu-latest
    secrets: inherit
    steps:
      - uses: ./.github/workflows/.earthly.yaml
        with:
          build-dir: alpine

  aria2:
    runs-on: ubuntu-latest
    needs:
      - alpine
    secrets: inherit
    steps:
      - uses: ./.github/workflows/.earthly.yaml
        continue-on-error: true
        with:
          build-dir: aria2
  asuswrt-merlin-build:
    runs-on: ubuntu-latest
    needs:
      - aria2
    secrets: inherit
    steps:
      - uses: ./.github/workflows/.earthly.yaml
        continue-on-error: true
        with:
          build-dir: asuswrt-merlin-build
  bandwagonmon:
    runs-on: ubuntu-latest
    needs:
      - asuswrt-merlin-build
    secrets: inherit
    steps:
      - uses: ./.github/workflows/.earthly.yaml
        continue-on-error: true
        with:
          build-dir: bandwagonmon
  caddy:
    runs-on: ubuntu-latest
    needs:
      - bandwagonmon
    secrets: inherit
    steps:
      - uses: ./.github/workflows/.earthly.yaml
        continue-on-error: true
        with:
          build-dir: caddy
  clash-meta:
    runs-on: ubuntu-latest
    needs:
      - caddy
    secrets: inherit
    steps:
      - uses: ./.github/workflows/.earthly.yaml
        continue-on-error: true
        with:
          build-dir: clash-meta
  confluence:
    runs-on: ubuntu-latest
    needs:
      - clash-meta
    secrets: inherit
    steps:
      - uses: ./.github/workflows/.earthly.yaml
        continue-on-error: true
        with:
          build-dir: confluence
  container-cli:
    runs-on: ubuntu-latest
    needs:
      - confluence
    secrets: inherit
    steps:
      - uses: ./.github/workflows/.earthly.yaml
        continue-on-error: true
        with:
          build-dir: container-cli
  ddns:
    runs-on: ubuntu-latest
    needs:
      - container-cli
    secrets: inherit
    steps:
      - uses: ./.github/workflows/.earthly.yaml
        continue-on-error: true
        with:
          build-dir: ddns
  demo:
    runs-on: ubuntu-latest
    needs:
      - ddns
    secrets: inherit
    steps:
      - uses: ./.github/workflows/.earthly.yaml
        continue-on-error: true
        with:
          build-dir: demo
  derper:
    runs-on: ubuntu-latest
    needs:
      - demo
    secrets: inherit
    steps:
      - uses: ./.github/workflows/.earthly.yaml
        continue-on-error: true
        with:
          build-dir: derper
  dnsacme:
    runs-on: ubuntu-latest
    needs:
      - derper
    secrets: inherit
    steps:
      - uses: ./.github/workflows/.earthly.yaml
        continue-on-error: true
        with:
          build-dir: dnsacme
  dockerhub:
    runs-on: ubuntu-latest
    needs:
      - dnsacme
    secrets: inherit
    steps:
      - uses: ./.github/workflows/.earthly.yaml
        continue-on-error: true
        with:
          build-dir: dockerhub
  idgen:
    runs-on: ubuntu-latest
    needs:
      - dockerhub
    secrets: inherit
    steps:
      - uses: ./.github/workflows/.earthly.yaml
        continue-on-error: true
        with:
          build-dir: idgen
  jira:
    runs-on: ubuntu-latest
    needs:
      - idgen
    secrets: inherit
    steps:
      - uses: ./.github/workflows/.earthly.yaml
        continue-on-error: true
        with:
          build-dir: jira
  makeself:
    runs-on: ubuntu-latest
    needs:
      - jira
    secrets: inherit
    steps:
      - uses: ./.github/workflows/.earthly.yaml
        continue-on-error: true
        with:
          build-dir: makeself
  nginx-singlepage:
    runs-on: ubuntu-latest
    needs:
      - makeself
    secrets: inherit
    steps:
      - uses: ./.github/workflows/.earthly.yaml
        continue-on-error: true
        with:
          build-dir: nginx-singlepage
  nodebuild:
    runs-on: ubuntu-latest
    needs:
      - nginx-singlepage
    secrets: inherit
    steps:
      - uses: ./.github/workflows/.earthly.yaml
        continue-on-error: true
        with:
          build-dir: nodebuild
  notibot:
    runs-on: ubuntu-latest
    needs:
      - nodebuild
    secrets: inherit
    steps:
      - uses: ./.github/workflows/.earthly.yaml
        continue-on-error: true
        with:
          build-dir: notibot
  open-vm-tools:
    runs-on: ubuntu-latest
    needs:
      - notibot
    secrets: inherit
    steps:
      - uses: ./.github/workflows/.earthly.yaml
        continue-on-error: true
        with:
          build-dir: open-vm-tools
  openjdk:
    runs-on: ubuntu-latest
    needs:
      - open-vm-tools
    secrets: inherit
    steps:
      - uses: ./.github/workflows/.earthly.yaml
        continue-on-error: true
        with:
          build-dir: openjdk
  osarch:
    runs-on: ubuntu-latest
    needs:
      - openjdk
    secrets: inherit
    steps:
      - uses: ./.github/workflows/.earthly.yaml
        continue-on-error: true
        with:
          build-dir: osarch
  poetbot:
    runs-on: ubuntu-latest
    needs:
      - osarch
    secrets: inherit
    steps:
      - uses: ./.github/workflows/.earthly.yaml
        continue-on-error: true
        with:
          build-dir: poetbot
  s2h:
    runs-on: ubuntu-latest
    needs:
      - poetbot
    secrets: inherit
    steps:
      - uses: ./.github/workflows/.earthly.yaml
        continue-on-error: true
        with:
          build-dir: s2h
  ssh:
    runs-on: ubuntu-latest
    needs:
      - s2h
    secrets: inherit
    steps:
      - uses: ./.github/workflows/.earthly.yaml
        continue-on-error: true
        with:
          build-dir: ssh

