name: mritd/alpine

on:
  schedule:
    - cron: '0 8 * * 1'
  workflow_dispatch:
    inputs:
      trigger:
        description: 'Manually trigger'
        required: true
        type: choice
        options:
          - build

jobs:
  alpine:
    runs-on: ubuntu-latest
    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
      FORCE_COLOR: 1
    steps:
    - uses: actions/checkout@v2
    - name: Put back the git branch into git (Earthly uses it for tagging)
      run: |
        branch=""
        if [ -n "$GITHUB_HEAD_REF" ]; then
          branch="$GITHUB_HEAD_REF"
        else
          branch="${GITHUB_REF##*/}"
        fi
        git checkout -b "$branch" || true
    - name: Docker Login
      run: docker login --username "$DOCKERHUB_USERNAME" --password "$DOCKERHUB_PASSWORD"
    - name: Install Task
      uses: arduino/setup-task@v1
    - name: Run Task
      working-directory: earthfiles
      run: task ${{ github.job }}
