name: mritd/alpine

on:
  schedule:
    - cron: '0 8 * * 1'
  workflow_dispatch:
    inputs:
      trigger:
        description: 'Manually trigger'
        required: true
        type: choice
        options:
          - build

jobs:
  alpine:
    runs-on: ubuntu-latest
    env:
      FORCE_COLOR: 1
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
      EARTHLY_RELEASE_URL: https://api.github.com/repos/earthly/earthly/releases/latest
    steps:
    - uses: actions/checkout@v2
    - name: Put back the git branch into git (Earthly uses it for tagging)
      run: |
        branch=""
        if [ -n "$GITHUB_HEAD_REF" ]; then
          branch="$GITHUB_HEAD_REF"
        else
          branch="${GITHUB_REF##*/}"
        fi
        git checkout -b "$branch" || true
    - name: Docker Login
      run: docker login --username "$DOCKERHUB_USERNAME" --password "$DOCKERHUB_PASSWORD"
    - name: Install Deps
      run: |
        sudp apt update -y
        sudo apt install curl jq qemu binfmt-support qemu-user-static -y
    - name: Install Earthly
      run: sudo curl -fsSL $(curl -fsSL ${EARTHLY_RELEASE_URL} | jq -r '.assets[].browser_download_url' | grep earthly-linux-amd64) > /usr/local/bin/earthly
    - name: Run Build
      working-directory: earthfiles/${{ github.job }}
      run: earthly --ci --allow-privileged --push +all
