name: mritd/aria2

on:
  workflow_call:
  workflow_dispatch:
    inputs:
      trigger:
        description: Manually trigger
        required: true
        type: choice
        options:
          - build

jobs:
  aria2:
    runs-on: ubuntu-latest
    secrets: inherit
    steps:
      - uses: ./.github/workflows/.earthly.yaml
        with:
          build-dir: aria2
