name: mritd/asuswrt-merlin-build

on:
  workflow_call:
  workflow_dispatch:
    inputs:
      trigger:
        description: Manually trigger
        required: true
        type: choice
        options:
          - build

jobs:
  asuswrt-merlin-build:
    runs-on: ubuntu-latest
    uses: ./.github/workflows/.earthly.yaml
    with:
      build-dir: asuswrt-merlin-build
