name: mritd/asuswrt-merlin-build

on:
  workflow_call:
  workflow_dispatch:
    inputs:
      trigger:
        description: Manually trigger
        required: true
        type: choice
        options:
          - build

jobs:
  asuswrt-merlin-build:
    uses: ./.github/workflows/.earthly.yaml
    secrets: inherit
    with:
      build-dir: asuswrt-merlin-build
