name: autobuild

concurrency: docker-image

on:
  schedule:
    - cron: '0 8 * * 1'
  workflow_dispatch:
    inputs:
      trigger:
        description: 'Manually trigger'
        required: true
        type: choice
        options:
          - build

env:
  FORCE_COLOR: 1
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}

jobs:
  alpine:
    needs: install-deps
    concurrency: docker-image
    steps:
    - name: Init
      uses: mritd/autobuild@master
    - name: Earthly Build
      working-directory: earthfiles/${{ github.job }}
      run: earthly --ci --allow-privileged --push +all

  certmonitor:
    needs: install-deps
    concurrency: docker-image
    steps:
    - name: Init
      uses: mritd/autobuild@master
    - name: Earthly Build
      working-directory: earthfiles/${{ github.job }}
      run: earthly --ci --allow-privileged --push +all
