name: mritd/certmonitor

on:
  schedule:
    - cron: '0 8 * * 1'
  workflow_dispatch:
    inputs:
      trigger:
        description: 'Manually trigger'
        required: true
        type: choice
        options:
          - build

env:
  FORCE_COLOR: 1
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}

jobs:
  certmonitor:
    runs-on: ubuntu-22.04
    concurrency: docker-image
    steps:
    - name: Init Earthly
      uses: mritd/init-earthly-action@main
    - name: Earthly Build
      working-directory: earthfiles/${{ github.job }}
      run: earthly --ci --allow-privileged --push +all
