name: mritd/clash-meta

on:
  schedule:
    - cron: 0 4 * * 1
  workflow_call:
  workflow_dispatch:
    inputs:
      trigger:
        description: Manually trigger
        required: true
        type: choice
        options:
          - build

jobs:
  clash-meta:
    uses: ./.github/workflows/.earthly.yaml
    secrets: inherit
    with:
      build-dir: clash-meta
