name: mritd/demo

on:
  workflow_call:
  workflow_dispatch:
    inputs:
      trigger:
        description: Manually trigger
        required: true
        type: choice
        options:
          - build

jobs:
  demo:
    runs-on: ubuntu-latest
    uses: ./.github/workflows/.earthly.yaml
    with:
      build-dir: demo
