name: mritd/nginx-singlepage

on:
  workflow_call:
  workflow_dispatch:
    inputs:
      trigger:
        description: Manually trigger
        required: true
        type: choice
        options:
          - build

jobs:
  nginx-singlepage:
    runs-on: ubuntu-latest
    uses: ./.github/workflows/.earthly.yaml
    secrets: inherit
    with:
      build-dir: nginx-singlepage
