name: mritd/notibot

on:
  workflow_call:
  workflow_dispatch:
    inputs:
      trigger:
        description: Manually trigger
        required: true
        type: choice
        options:
          - build

jobs:
  notibot:
    uses: ./.github/workflows/.earthly.yaml
    secrets: inherit
    with:
      build-dir: notibot
