name: mritd/open-vm-tools

on:
  workflow_call:
  workflow_dispatch:
    inputs:
      trigger:
        description: Manually trigger
        required: true
        type: choice
        options:
          - build

jobs:
  open-vm-tools:
    runs-on: ubuntu-latest
    secrets: inherit
    steps:
      - uses: ./.github/workflows/.earthly.yaml
        with:
          build-dir: open-vm-tools
