name: mritd/openjdk

on:
  workflow_call:
  workflow_dispatch:
    inputs:
      trigger:
        description: Manually trigger
        required: true
        type: choice
        options:
          - build

jobs:
  openjdk:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/workflows/.earthly.yaml
        secrets: inherit
        with:
          build-dir: openjdk
