name: mritd/osarch

on:
  workflow_call:
  workflow_dispatch:
    inputs:
      trigger:
        description: Manually trigger
        required: true
        type: choice
        options:
          - build

jobs:
  osarch:
    runs-on: ubuntu-latest
    uses: ./.github/workflows/.earthly.yaml
    with:
      build-dir: osarch
