name: mritd/ssh

on:
  workflow_call:
  workflow_dispatch:
    inputs:
      trigger:
        description: Manually trigger
        required: true
        type: choice
        options:
          - build

jobs:
  ssh:
    runs-on: ubuntu-latest
    uses: ./.github/workflows/.earthly.yaml
    secrets: inherit
    with:
      build-dir: ssh
