name: mritd/tpclash

on:
  workflow_call:
  workflow_dispatch:
    inputs:
      trigger:
        description: Manually trigger
        required: true
        type: choice
        options:
          - build

jobs:
  tpclash:
    uses: ./.github/workflows/.earthly.yaml
    secrets: inherit
    with:
      build-dir: tpclash
